[manager]
prepend_keymap = [
  # simple settings
  { on = [ "g", "l" ],       run = "cd ~/.local",             desc = "~/.local"                   },
  { on = [ "g", "n" ],       run = "cd ~/nixos",              desc = "~/nixos"                    },
  { on = [ "g", "p" ],       run = "cd ~/secondary_drive",    desc = "~/secondary_drive"          },
  { on = [ "g", "u" ],       run = "cd ~/usb",                desc = "~/usb"                      },
  { on = [ "g", "d" ],       run = "cd ~/downloads",          desc = "~/downloads"                },
  { on = [ "g", "c" ],       run = "cd ~/.config",            desc = "~/.config"                  },
  { on = [ "g", "h" ],       run = "cd ~/",                   desc = "~"                          },

  # complex settings
  { on = [ "c", "a" ],       run = "plugin ouch --args=zip",  desc = "Compress selected" },
  { on = [ "c", "m" ],       run = "plugin chmod", desc = "chmod on selected"},

  { on = ["d", "d"], run = "remove", desc = "move to trash" },
  { on = ["d", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },

  { on = [ "c", "q" ],       run = "quit", desc = "quit"}

]
